algo = (input("digite algo: "))
print(f"O tipo primitivo desse algo é {type(algo)} ")
print(f"Só tem espaço? {algo.isspace()} ")
print(f"É um número? {algo.isnumeric()}")
print(f"É alfabético? {algo.isalpha()}")
print(f"É alfanumérico? {algo.isalnum()}")
print(f"Esta em minuscula? {algo.islower()}")
print(f"Esta em maiscula? {algo.isupper()}")
print(f"Esta capitalizada? {algo.istitle()}")